---
- name: Install Sensu
  apt: name={{ item }} state=present
  with_items:
   - sensu
   - ruby
   - ruby-dev
   - build-essential
   - uchiwa
   - postfix
   - mailutils

- name: Install sensu gem
  gem: name={{ item }} state=present
  with_items:
  - mixlib-cli
  - sensu-plugin

- name: Create SSL directory for Sensu
  file: path=/etc/sensu/ssl state=directory

- name: Copy cert.pem to /etc/sensu/ssl
  template: src=cert.pem dest=/etc/sensu/ssl/cert.pem

- name: Copy key.pem to /etc/sensu/ssl
  template: src=key.pem dest=/etc/sensu/ssl/key.pem

- name: Enable the Sensu services to start automatically
  shell: update-rc.d {{ item }} defaults
  with_items:
  - sensu-server
  - sensu-client
  - sensu-api
  changed_when: False

- name: Change uchinwa.json
  template: src=uchiwa.j2 dest=/etc/sensu/uchiwa.json
  notify: restart sensu

- name: Adding api.json
  template: src=api.j2 dest=/etc/sensu/conf.d/api.json
  notify: restart sensu

- name: Adding redis.json
  template: src=redis.j2 dest=/etc/sensu/conf.d/redis.json
  notify: restart sensu

- name: Adding client.json
  template: src=client.j2 dest=/etc/sensu/conf.d/client.json
  notify: restart sensu

- name: Adding rabbitmq.json
  template: src=rabbitmq.j2 dest=/etc/sensu/conf.d/rabbitmq.json
  notify: restart sensu

- name: Adding an email handler
  template: src=email-handler.j2 dest=/etc/sensu/conf.d/handler_email.json
  notify: restart sensu
