---
- name: Add the Sensu APT key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: Add the Sensu source to the APT source list
  apt_repository: repo="deb http://repos.sensuapp.org/apt sensu main" state=present

- name: Install Sensu
  apt: name={{ item }} state=present
  with_items:
   - sensu
   - ruby
   - ruby-dev
   - build-essential
   - uchiwa
   - postfix
   - mailutils

- name: Install sensu gem
  gem: name={{ item }} state=present
  with_items:
  - mixlib-cli
  - sensu-plugin
  - mail
  - timeout

- name: Create SSL directory for Sensu
  file: path=/etc/sensu/ssl state=directory

- name: Copy cert.pem to /etc/sensu/ssl
  template: src=cert.pem dest=/etc/sensu/ssl/cert.pem

- name: Copy key.pem to /etc/sensu/ssl
  template: src=key.pem dest=/etc/sensu/ssl/key.pem

- name: Enable the Sensu services to start automatically
  shell: update-rc.d {{ item }} defaults
  with_items:
  - rabbitmq-server
  - redis-server
  - sensu-server
  - sensu-client
  - sensu-api
  - uchiwa
  changed_when: False

- name: Change uchinwa.json
  template: src=uchiwa.j2 dest=/etc/sensu/uchiwa.json

- name: Adding api.json
  template: src=api.j2 dest=/etc/sensu/conf.d/api.json

- name: Adding redis.json
  template: src=redis.j2 dest=/etc/sensu/conf.d/redis.json

- name: Adding client.json
  template: src=client.j2 dest=/etc/sensu/conf.d/client.json

- name: Adding rabbitmq.json
  template: src=rabbitmq.j2 dest=/etc/sensu/conf.d/rabbitmq.json

- name: Adding an email handler
  template: src=email-handler.j2 dest=/etc/sensu/conf.d/handler_email.json

- name: Create handlers directory for Sensu
  file: path=/etc/sensu/handlers state=directory

- name: Adding mailer.rb
  template: src=mailer.j2 dest=/etc/sensu/handlers/mailer.rb

- name: Adding mailer.json
  template: src=mailer-json.j2 dest=/etc/sensu/conf.d/mailer.json

- name: Adding default.json
  template: src=default.json dest=/etc/sensu/conf.d/default.json

- name: Restart all services
  service: name={{ item }} state=restarted
  with_items:
  - sensu-server
  - sensu-client
  - sensu-api
  - uchiwa
