---
- name: Add the RabbitMQ APT key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Add the RabbitMQ source to the APT source list
  apt_repository: repo="deb http://www.rabbitmq.com/debian/ testing main" state=present

- name: Add the Sensu APT key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: Add the Sensu source to the APT source list
  apt_repository: repo="deb http://repos.sensuapp.org/apt sensu main" state=present

- name: Install RabbitMQ
  apt: name={{ item }} state=present
  with_items:
   - erlang-nox
   - rabbitmq-server

- name: Configure RabbitMQ
  template: src=rabbitmq.conf dest=/etc/rabbitmq/rabbitmq.config

- name: Restart RabbitMQ services
  service: name={{ item }} state=restarted
  with_items:
  - rabbitmq-server

- name: Create a RabbitMQ virtual host
  shell: rabbitmqctl add_vhost /sensu
  ignore_errors: True
  register: error1

- debug: var=error1

- name: Create a user for Sensu
  shell: rabbitmqctl add_user sensu sensu
  ignore_errors: True
  register: error2

- debug: var=error2

- name: Set permissions Sensu user
  shell: rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"
  changed_when: False

- name: Install Redis
  apt: name={{ item }} state=present
  with_items:
  - redis-server

- name: Configuring redis
  template: src=redis.conf dest=/etc/redis/redis.conf

- name: Restart Redis services
  service: name={{ item }} state=restarted
  with_items:
  - redis-server

- name: Install Sensu
  apt: name={{ item }} state=present
  with_items:
   - sensu
   - ruby
   - ruby-dev
   - build-essential
   - uchiwa
   - postfix
   - mailutils

- name: Install sensu gem
  gem: name=sensu-plugin state=present

- name: Enable the Sensu services to start automatically
  shell: update-rc.d {{ item }} defaults
  with_items:
  - rabbitmq-server
  - redis-server
  - sensu-server
  - sensu-client
  - sensu-api
  - uchiwa
  changed_when: False

- name: Change uchinwa.json
  template: src=uchiwa.j2 dest=/etc/sensu/uchiwa.json

- name: Adding api.json
  template: src=api.j2 dest=/etc/sensu/conf.d/api.json

- name: Adding redis.json
  template: src=redis.j2 dest=/etc/sensu/conf.d/redis.json

- name: Adding client.json
  template: src=client.j2 dest=/etc/sensu/conf.d/client.json

- name: Adding rabbitmq.json
  template: src=rabbitmq.j2 dest=/etc/sensu/conf.d/rabbitmq.json

- name: Adding an email handler
  template: src=email-handler.j2 dest=/etc/sensu/conf.d/handler_email.json

- name: Restart all services
  service: name={{ item }} state=restarted
  with_items:
  - rabbitmq-server
  - redis-server
  - sensu-server
  - sensu-client
  - sensu-api
  - uchiwa
