- name: Adding RabbitMQ repo
  template: src=rabbitmq-repo.j2 dest=/etc/apt/sources.list.d/rabbitmq.list

- name: Download and add the signing key for RabbitMQ
  template: src=rabbitmq-signing-key-public.j2 dest=/tmp/rabbitmq-signing-key-public.asc

- shell: sudo apt-key add /tmp/rabbitmq-signing-key-public.asc

#- name: update_cache
#  apt: update_cache=yes

- name: Install RabbitMQ
  apt: name={{ item }} state=present
  with_items:
   - rabbitmq-server 
   - erlang-nox
  notify: start rabbitmq-server

- name: Download SSL certs 
  get_url: url=http://sensuapp.org/docs/0.13/tools/ssl_certs.tar dest=/tmp/

- name: Extract SSL certs
  shell: tar -xvf /tmp/ssl_certs.tar -C /tmp
  shell: cd /tmp/ssl_certs && sudo ./ssl_certs.sh generate
  shell: sudo mkdir -p /etc/rabbitmq/ssl && sudo cp /tmp/ssl_certs/sensu_ca/cacert.pem /tmp/ssl_certs/server/cert.pem /tmp/ssl_certs/server/key.pem /etc/rabbitmq/ssl

- name: Configure RabbitMQ
  template: src=rabbitmq.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq-server

- name: Adding Sensu user in RabbitMQ
  shell: sudo rabbitmqctl add_vhost /sensu
  shell: sudo rabbitmqctl add_user sensu {{ set_sensu_password }}
  shell: sudo rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"

- name: Install Redis
  apt: name={{ item }} state=present
  with_items:
   - redis-server
  notify: start redis-server

- name: Add Sensu key
  shell: wget -q http://repos.sensuapp.org/apt/pubkey.gpg -O- | sudo apt-key add -

- name: Adding Sensu repo
  template: src=sensu-repo.j2 dest=/etc/apt/sources.list.d/sensu.list

#- name: update_cache
#  apt: update_cache=yes

- name: Install Sensu
  apt: name={{ item }} state=present
  with_items:
   - sensu 
   - uchiwa
- shell: sudo mkdir -p /etc/sensu/ssl && sudo cp /tmp/ssl_certs/client/cert.pem /tmp/ssl_certs/client/key.pem /etc/sensu/ssl


- template: src=rabbitmq-template.j2 dest=/etc/sensu/conf.d/rabbitmq.json
- template: src=redis.j2 dest=/etc/sensu/conf.d/redis.json
- template: src=api.j2 dest=/etc/sensu/conf.d/api.json
- template: src=uchiwa.j2 dest=/etc/sensu/conf.d/uchiwa.json
- template: src=clients.j2 dest=/etc/sensu/conf.d/client.json

- name: Sensu at startup
  shell: sudo update-rc.d sensu-server defaults
  shell: sudo update-rc.d sensu-client defaults
  shell: sudo update-rc.d sensu-api defaults
  shell: sudo update-rc.d uchiwa defaults
  notify: start sensu-server 
  notify: start sensu-client 
  notify: start sensu-api 
  notify: start uchiwa 



