---
- name: Install ntp
  apt: name={{ item }} state=present
  with_items:
  - ntp

- name: Configure ntp
  template: src=ntp.j2 dest=/etc/ntp.conf

- name: Configure timezone
  template: src=timezone.j2 dest=/etc/timezone

- name: Remove default time zone
  file: path=/etc/localtime state=absent 

- name: Set local time as "{{ timezone }}"
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link

- name: Restart ntp
  service: name=ntp state=restarted
