- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted

- name: restart redis-server
  service: name=redis-server state=restarted

- name: restart sensu
  service: name={{ item }} state=restarted
  with_items:
  - sensu-server
  - sensu-client
  - sensu-api
  - uchiwa

- name: stop nginx
  service: name=nginx state=stopped

- name: restart nginx
  service: name=nginx state=restarted
